NDefines.NMilitary.PROMOTE_LEADER_CP_COST = 15.0
NDefines.NMilitary.UNIT_LEADER_TRAIT_SLOT_PER_LEVEL = { 0.75, 0.75, 0.75, 0.0 }
NDefines.NMilitary.UNIT_LEADER_ASSIGN_TRAIT_COST = 5.0
NDefines.NMilitary.COST_INCREASE_PER_ACTIVE_MEDAL = 0.20