NDefines.NMilitary.PROMOTE_LEADER_CP_COST = 20.0
NDefines.NMilitary.UNIT_LEADER_TRAIT_SLOT_PER_LEVEL = { 0.5, 0.65, 0.6, 0.0 }
NDefines.NMilitary.UNIT_LEADER_ASSIGN_TRAIT_COST = 5.0
NDefines.NMilitary.COST_INCREASE_PER_ACTIVE_MEDAL = 0.20